# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Mantenimiento Windows v2.0
# Build command: pyinstaller mantenimiento_windows.spec


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('services', 'services'),
        ('routes', 'routes'),
        ('config.py', '.'),
    ],
    hiddenimports=[
        'flask',
        'jinja2',
        'markupsafe',
        'psutil',
        'services.command_runner',
        'services.permissions',
        'services.system_info',
        'services.cleanup',
        'services.repair',
        'services.network_tools',
        'services.windows_update',
        'services.power_tools',
        'services.graphics_tools',
        'services.antivirus_tools',
        'services.restore_tools',
        'services.drivers',
        'services.reports',
        'routes.dashboard',
        'routes.diagnostics',
        'routes.cleanup',
        'routes.repair',
        'routes.network',
        'routes.update',
        'routes.power',
        'routes.drivers',
        'routes.security',
        'routes.reports',
        'routes.advanced',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pydoc',
        'doctest',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MantenimientoWindows',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
)
